Repository FootStepteam/footstep_FE, pull requests merged in 2023-07, with the labels that each got.

#98 ⚡️ Feature: 채팅 기능 구현 개선 및 UI작업
  src/components/planShareRoom/Chat.tsx
  src/main.tsx
Labels: function, UI

#99 💚 Fix: build 에러 해결
  package-lock.json
  src/api/scheduleAPI.ts
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareRoom/Chat.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/placeSearchArea/PlaceRecommendList.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/components/planShareRoom/scheduleArea/ScheduleMemo.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/hooks/usePlanDate.ts
  src/type/kakaoMap.ts
  src/type/shareRoom.ts
  tsconfig.json
Labels: bug

#101 Feature/style
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/SignInAndUp.tsx
  src/components/main/Start.tsx
Labels: UI

#103 Feature/chat
  package-lock.json
  package.json
  src/api/chatAPI.ts
  src/api/kakaoLoginAPI.ts
  src/components/planShareRoom/Chat.tsx
  vite.config.ts
  yarn.lock
Labels: function

#104 Fix: 토큰 유효성 검사 및 재발급, 에러코드별 알람 출력 함수 추가
  src/api/chatAPI.ts
  src/api/communityAPI.ts
  src/api/destinationAPI.ts
  src/api/memberAPI.ts
  src/api/newPostAPI.ts
  src/api/postAPI.ts
  src/api/profileAPI.ts
  src/api/recommendAPI.ts
  src/api/scheduleAPI.ts
  src/api/shareRoomAPI.ts
  src/api/tokenAPI.ts
  src/components/planShareEntrance/planList/PlanListHeader.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/hooks/useLoginState.ts
  src/hooks/useManageSchdule.ts
  src/hooks/useShareRoomForm.ts
  src/utils/errorMsgAlert.ts
Labels: bug, function

#105 ⚡️ Feature: get saved chat messages
  src/api/chatAPI.ts
  src/api/kakaoLoginAPI.ts
  src/components/planShareRoom/Chat.tsx
Labels: function

#106 로그인 페이지 UI 수정 및 코드 리팩토링
  src/api/communityAPI.ts
  src/api/emailLoginAPI.ts
  src/api/postAPI.ts
  src/assets/kakao.svg
  src/components/common/header/headerLeft/Menu.tsx
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoLoginButton.tsx
  src/components/login/LoginHeader.tsx
  src/components/login/SignUpLink.tsx
  src/pages/LoginPage.tsx
  src/utils/errorMsgAlert.ts
  vercel.json
Labels: function, UI(Component)

#107 🐛 Fix: solve save token error
  src/components/login/EmailLoginForm.tsx
Labels: bug

#109 회원가입 전체적인 로직 변경 및 UI 수정, 회원가입 성공 페이지 추가
  src/App.tsx
  src/api/userSignUp.ts
  src/components/login/KakaoLoginButton.tsx
  src/components/signUp/SuccessSignUp.tsx
  src/components/signUp/signUpForm.tsx
  src/hooks/useSignUpForm.ts
  src/pages/SignUp.tsx
  src/store/useSignUpForm.ts
  src/utils/errorMsgAlert.ts
Labels: function, UI(Component)

#110 💄 Design: 마이페이지, 프로필 수정 페이지 UI 수정 및 헤더 컴포넌트 UI 수정
  src/components/common/header/HeaderContainer.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/main/Start.tsx
  src/components/planShareEntrance/PlanShareEntrance.tsx
  src/components/profile/Profile.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/ParticipatingPlan.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/components/profileEdit/Tab.tsx
  src/components/profileEdit/passwordEdit/PasswordEdit.tsx
  src/pages/CommunityPage.tsx
  src/pages/PostPage.tsx
Labels: UI(Component)

#111 💄 Design: 홈 MAP 사진 크기 수정
  src/components/main/Start.tsx
Labels: UI(Component)

#112 💄 Design: 로그인 버튼 영역 css 수정
  src/components/common/header/headerRight/SignInAndUp.tsx
Labels: UI(Component)

#113 💄 Design: header css 수정
  src/components/common/header/headerLeft/Menu.tsx
Labels: UI(Component)

#114 🚧 Fix: websocket 주소 변경, 카카오맵 환경변수 설정
  index.html
  src/components/planShareRoom/Chat.tsx
Labels: function

#115 🐛 Fix: fix index.html for release
  index.html
Labels: release

#116 💄 Design: 공유방 입장 페이지 css 수정
  src/components/common/header/headerRight/SignInAndUp.tsx
  src/components/planShareEntrance/createShareRoomModal/CreateShareRoomModal.tsx
  src/components/planShareEntrance/planList/ExistsPlan.tsx
  src/components/planShareEntrance/planList/PlanList.tsx
  src/components/planShareEntrance/planList/PlanListHeader.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
Labels: UI(Component)

#117 🐛 Fix: 공유방 검색 후 존재하지 않았을 때 오류 수정
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
Labels: bug

#118 💄 Style: 채팅 메세지 작성구역 아웃라인 제거
  src/components/planShareRoom/Chat.tsx
Labels: UI

#119 🐛 Fix: 공유방 검색 시 오류 수정
  src/api/shareRoomAPI.ts
Labels: bug

#120 💄 Design: 검색결과 css 수정
  src/components/planShareEntrance/planList/SearchResult.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
Labels: UI(Component)

#121 Feature/edit
  src/api/passwordAPI.ts
  src/api/profileAPI.ts
  src/api/shareRoomAPI.ts
  src/api/userSignUp.ts
  src/components/newPost/EditorArea.tsx
  src/components/planShareRoom/Chat.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/components/profileEdit/passwordEdit/PasswordEdit.tsx
  src/state/memberInfo.ts
  src/store/shareRoomInfo.ts
  src/type/profile.ts
Labels: function

#122 Feature/edit
  src/api/memberAPI.ts
  src/api/newPostAPI.ts
  src/api/postAPI.ts
  src/api/profileAPI.ts
  src/api/shareRoomAPI.ts
  src/components/community/Lists.tsx
  src/components/community/SortButtons.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/Post.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/components/profileEdit/passwordEdit/PasswordEdit.tsx
  src/components/profileEdit/secession/Secession.tsx
  src/hooks/useEditor.ts
Labels: function

#123 👽️ Fix/select error
  src/components/planShareEntrance/planList/ExistsPlan.tsx
  src/components/planShareEntrance/planList/PlanListContent.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/ParticipatingPlan.tsx
  src/store/getShareRoomList.ts
  src/type/shareRoom.ts
Labels: bug

#124 ✨ Feature: 회원정보 수정 기능 수정,
  src/api/profileAPI.ts
  src/components/profileEdit/edit/ProfileEditForm.tsx
Labels: function

#125 Fix/error
  src/components/newPost/EditorArea.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/type/shareRoom.ts
Labels: bug

#126 🐛 Fix: fix bug for release
  src/store/searchShareRoom.ts
  src/store/shareRoomInfo.ts
  src/type/shareRoom.ts
Labels: bug

#127 🐛 Fix: fix bug
  src/hooks/useEditor.ts
  src/store/searchShareRoom.ts
  src/store/shareRoomInfo.ts
Labels: bug

#128 ✨ Feature: 게시글 조회, 페이지네이션, 조건 별 검색 기능 추가
  src/api/communityAPI.ts
  src/assets/footStepLogo.svg
  src/components/common/header/headerLeft/Logo.tsx
  src/components/community/Category.tsx
  src/components/community/Community.tsx
  src/components/community/Lists.tsx
  src/components/community/Pagination.tsx
  src/components/community/SearchBar.tsx
  src/components/community/SearchSection.tsx
  src/components/community/SortButtons.tsx
  src/components/login/LoginHeader.tsx
  src/components/signUp/SuccessSignUp.tsx
  src/pages/CommunityPage.tsx
  src/state/condition.ts
  src/store/postList.ts
  src/type/communityPage.ts
Labels: bug, function, UI(Component)

#129 💄 Design: 회원가입 페이지 로고 추가
  src/components/signUp/signUpForm.tsx
Labels: UI(Component)

#130 🐛 Fix: 좋아요 오류 수정
  src/components/community/Lists.tsx
  src/components/community/postPage/Like.tsx
  src/components/community/postPage/Post.tsx
  src/type/communityPage.ts
Labels: bug

#131 🐛 Fix: 일정공유방 에러
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/components/planShareRoom/scheduleArea/ScheduleMemo.tsx
  src/hooks/useManageSchdule.ts
  src/hooks/useShareRoomForm.ts
  src/state/componentOpenState.ts
  src/state/scheduleMarkerState.ts
Labels: bug

#132 🐛 Fix: 메모 저장 안되는 오류 수정
  src/components/planShareRoom/scheduleArea/ScheduleMemo.tsx
Labels: bug

#133 🐛 Fix: error solve
  src/calender.css
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/state/scheduleMarkerState.ts
Labels: bug

#134 🐛 Fix: error solve
  src/api/profileAPI.ts
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
Labels: bug

#135 🐛 Fix: error solve
  src/hooks/useShareRoomForm.ts
  src/utils/formValidationCheck.ts
Labels: bug

#136 🐛 Fix: error pagination
  src/components/community/Lists.tsx
Labels: bug

#137 🐛 Fix: 최초 게시글 조회 시 최신순으로 조회되지 않는 오류 수정
  src/components/community/Lists.tsx
  src/type/communityPage.ts
Labels: bug

#138 🐛 Fix: 커뮤니티 타입 오류 수정
  src/components/community/Lists.tsx
  src/components/community/Pagination.tsx
  src/components/community/SearchBar.tsx
  src/components/community/SortButtons.tsx
  src/type/communityPage.ts
Labels: bug

#139 🐛 Fix: API 변경으로 인해 코드 수정
  src/api/communityAPI.ts
  src/api/postAPI.ts
Labels: bug

#140 🐛 Fix: 회원탈퇴 버그 수정
  src/components/profileEdit/secession/Secession.tsx
Labels: bug

#141 💄 Design: 게시글 작성, 게시글 상세조회 CSS 수정
  src/components/community/Lists.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/Like.tsx
  src/components/community/postPage/Post.tsx
  src/components/community/postPage/PostEditDelete.tsx
  src/components/newPost/EditorArea.tsx
Labels: UI(Component)

#142 💄 Design: 게시글 수정 페이지 css 수정
  src/components/community/postPage/EditPost.tsx
  src/components/community/postPage/PostEditDelete.tsx
Labels: UI(Component)

#143 Feature/fix
  src/components/profileEdit/secession/Secession.tsx
  src/utils/errorMsgAlert.ts
Labels: bug

#144 🐛 Fix: 게시글 수정 오류 해결
  src/api/postAPI.ts
  src/components/community/postPage/EditPost.tsx
Labels: bug

#145 💄 Design: favicon 수정
  index.html
Labels: UI(Component)

#146 ♻️ Refactor: 1차 Refactoring
  src/components/common/footer/FooterLink.tsx
  src/components/common/header/HeaderContainer.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/headerRight/SignInAndUp.tsx
  src/constants/initial.ts
  src/hooks/useLoginState.ts
  src/hooks/usePlanDate.ts
  src/hooks/useRequireAuth.ts
  src/pages/NewPost.tsx
  src/pages/PasswordEditPage.tsx
  src/pages/PlanShareEntrancePage.tsx
  src/pages/PlanShareRoomPage.tsx
  src/pages/ProfileEditPage.tsx
Labels: refactor

#147 🐛 Fix: 페이지별 권한 오류 수정
  src/hooks/useRequireAuth.ts
Labels: bug

#148 🐛 Fix: 페이지별 입장 권한 오류 수정
  src/components/community/Lists.tsx
  src/components/newPost/EditorArea.tsx
  src/hooks/useRequireAuth.ts
Labels: bug

#149 Feature/fix
  package-lock.json
  package.json
  src/components/community/postPage/EditPost.tsx
  src/components/planShareRoom/Chat.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  tailwind.config.js
  yarn.lock
Labels: bug

#150 Feature/fix
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/hooks/useLoginState.ts
  src/hooks/useRequireAuth.ts
Labels: bug

#151 🐛 Fix: check error
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
Labels: bug

#152 Feature/fix
  src/components/profileEdit/Tab.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/components/profileEdit/passwordEdit/PasswordEdit.tsx
  src/components/signUp/signUpForm.tsx
  src/hooks/useSignUpForm.ts
  src/type/signUp.ts
Labels: bug, function, refactor

#153 ✨ Feature: 실시간 일정 변경 기
  src/api/destinationAPI.ts
  src/api/shareRoomAPI.ts
  src/components/common/calendar/Calendar.tsx
  src/components/planShareEntrance/planList/SearchResult.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceRecommendList.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaHeader.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchCategory.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/useManageSchdule.ts
  src/hooks/usePlanDate.ts
  src/hooks/useSchdule.ts
  src/hooks/useShareRoomForm.ts
  src/state/scheduleMarkerState.ts
  src/store/getShareRoomList.ts
  src/store/scheduleList.ts
  src/store/searchShareRoom.ts
  src/store/shareRoomForm.ts
  src/store/shareRoomInfo.ts
  src/type/planShareRoom.ts
  src/utils/calculateDays.ts
  src/utils/formValidationCheck.ts
Labels: function

#154 💄 Design: 마이페이지 내소개 css 수정
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
Labels: UI(Component)

#155 💄 Design: add scrollbar-hide
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
Labels: UI(Component)

#156 🐛 Fix: 목적지 추가, 삭제 시 마커 추가 안되는 오류 수정
  src/components/planShareRoom/PlanShareRoom.tsx
Labels: bug

#157 ✨ Feature: 추천경로 일정설정, 일정완료 시 실시간 변경 로직 추가
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/useSchdule.ts
Labels: function

#158 Feature/responsive
  src/api/chatAPI.ts
  src/components/community/Lists.tsx
  src/components/community/SearchBar.tsx
  src/components/community/SearchSection.tsx
  src/components/community/SortButtons.tsx
  src/components/community/postPage/EditPost.tsx
  src/components/community/postPage/Post.tsx
  src/components/newPost/EditorArea.tsx
  src/components/profile/Profile.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/NotExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/ParticipatingPlan.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/components/profileEdit/passwordEdit/PasswordEdit.tsx
  src/components/profileEdit/secession/Secession.tsx
Labels: UI
