Repository FootStepteam/footstep_FE, pull requests merged in 2023-06, with the labels that each got.

#13 사용자 프로필 페이지 추가
  package-lock.json
  src/App.tsx
  src/assets/rightArrow.svg
  src/assets/temporary/nature-6517866_1920.jpg
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/profile/Profile.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/NotExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/ParticipatingPlan.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/pages/UserProfilePage.tsx
  tailwind.config.js
  yarn.lock
Labels: UI(Component)

#15 커뮤니티 페이지 추가
  src/App.tsx
  src/assets/like.svg
  src/components/community/Category.tsx
  src/components/community/Lists.tsx
  src/components/community/SearchBar.tsx
  src/main.tsx
  src/pages/CommunityPage.tsx
Labels: UI(Component)

#17 로그인 페이지 추가 작업
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoLoginButton.tsx
  src/pages/LoginPage.tsx
  yarn.lock
Labels: UI(Component)

#20 일정 공유 입장 페이지 추가
  src/App.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/planShareEntrance/PlanShareEntrance.tsx
  src/components/planShareEntrance/codeField/CodeField.tsx
  src/components/planShareEntrance/planList/PlanList.tsx
  src/components/planShareEntrance/planList/planContent/ExistsPlan.tsx
  src/components/planShareEntrance/planList/planContent/NotExistsPlan.tsx
  src/components/planShareEntrance/planList/planContent/PlanListContent.tsx
  src/components/planShareEntrance/planList/planHeader/PlanListHeader.tsx
  src/pages/PlanShareEntrancePage.tsx
  tailwind.config.js
Labels: UI(Component)

#28 About페이지(홈경로) 전체적인 UI 수정
  src/App.tsx
  src/assets/footstep.svg
  src/assets/line.svg
  src/assets/map.svg
  src/assets/mapChat.svg
  src/components/common/header/HeaderContainer.tsx
  src/components/main/Banner.tsx
  src/components/main/Content.tsx
  src/components/main/Problem.tsx
  src/components/main/Resolve.tsx
  src/components/main/Start.tsx
  src/components/main/Step.tsx
  src/pages/AboutPage.tsx
Labels: UI(Component)

#25 커뮤니티 페이지 기능 구현
  src/components/community/Category.tsx
  src/components/community/Lists.tsx
  src/components/community/SearchBar.tsx
  src/pages/CommunityPage.tsx
Labels: function

#29 공통 컴포넌트(Header, Footer) Style 변경
  src/components/common/footer/Footer.tsx
  src/components/common/footer/FooterLink.tsx
  src/components/common/header/HeaderContainer.tsx
  src/components/common/header/headerLeft/LeftContainer.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/RightContainer.tsx
  src/components/main/Content.tsx
  src/components/main/Start.tsx
Labels: UI(Component)

#31 Feature: 로그인/회원가입 버튼 클릭 시 로그인 페이지로 이동되게 Route 수정
  src/components/common/header/headerLeft/LeftContainer.tsx
  src/components/common/header/headerLeft/Logo.tsx
  src/components/common/header/headerRight/SignInAndUp.tsx
Labels: bug, function

#26 로그인 페이지 UI 수정
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoLoginButton.tsx
  src/pages/LoginPage.tsx
Labels: UI(Component)

#32 Fix: key설정을 해주지 않아 오류가 발생하여 key추가 하여 오류 해결
  src/components/planShareEntrance/planList/planContent/ExistsPlan.tsx
Labels: bug

#34 일정 공유방 생성 모달 및 모달에서 사용하는 calendar 추가
  .eslintrc.cjs
  package-lock.json
  package.json
  src/assets/blackCalendar.svg
  src/assets/bottomArrow.svg
  src/assets/close.svg
  src/calender.css
  src/components/planShareEntrance/PlanShareEntrance.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareEntrance/createShareRoomModal/Close.tsx
  src/components/planShareEntrance/createShareRoomModal/CreateShareRoomModal.tsx
  src/components/planShareEntrance/createShareRoomModal/PlanDate.tsx
  src/components/planShareEntrance/createShareRoomModal/Title.tsx
  src/components/planShareEntrance/planList/planHeader/PlanListHeader.tsx
  src/main.tsx
  src/pages/PlanShareEntrancePage.tsx
  src/state/createModalOpen.ts
  tailwind.config.js
  yarn.lock
Labels: UI(Component)

#35 Fix: react-calendar에서 선택한 value값 type오류로 인해 type 재지정
  src/components/planShareEntrance/createShareRoomModal/PlanDate.tsx
Labels: bug

#38 일정공유방 입장 페이지에서 사용되는 기능들 추가
  src/api/shareRoomAPI.ts
  src/components/common/spinner/Spinner.tsx
  src/components/planShareEntrance/PlanShareEntrance.tsx
  src/components/planShareEntrance/codeField/CodeField.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareEntrance/createShareRoomModal/CreateShareRoomModal.tsx
  src/components/planShareEntrance/createShareRoomModal/PlanDate.tsx
  src/components/planShareEntrance/createShareRoomModal/Title.tsx
  src/components/planShareEntrance/planList/PlanList.tsx
  src/components/planShareEntrance/planList/planContent/ExistsPlan.tsx
  src/components/planShareEntrance/planList/planContent/PlanListContent.tsx
  src/components/planShareEntrance/planList/planContent/SearchResult.tsx
  src/components/planShareEntrance/planList/planHeader/PlanListHeader.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
  src/main.tsx
  src/store/createShareRoomFormValue.ts
  src/store/searchShareRoom.ts
  src/type/shareRoom.ts
  tailwind.config.js
Labels: function

#40 일정공유방 사이드바 기본 UI구현
  src/App.tsx
  src/components/login/KakaoLoginButton.tsx
  src/components/planShareRoom/Example.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/sideBarComponents/DaySelect.tsx
  src/components/planShareRoom/sideBarComponents/PlaceLists.tsx
  src/components/planShareRoom/sideBarComponents/SideBarHeader.tsx
  src/components/planShareRoom/sideBarComponents/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/sideBarComponents/placeSearchArea/PlaceSearchBar.tsx
  src/components/planShareRoom/sideBarComponents/placeSearchArea/PlaceSearchCategory.tsx
  src/components/planShareRoom/sideBarComponents/placeSearchArea/PlaceSearchLists.tsx
  src/pages/PlanShareRoomPage.tsx
Labels: UI(Component)

#42 카카오 맵 API 추가
  index.html
  src/components/planShareRoom/map/Map.tsx
  src/pages/PlanShareRoomPage.tsx
Labels: UI(Component)

#44 로그인 페이지 기능 개발
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoLoginButton.tsx
  src/components/login/LoginHeader.tsx
  src/components/login/SignUpLink.tsx
  src/pages/LoginPage.tsx
  src/state/loginState.ts
  src/type/emailLogin.ts
  vite.config.ts
Labels: function

#47 로그인 완료시 쿠키 설정 기능 구현
  package-lock.json
  package.json
  src/api/emailLoginAPI.ts
  src/api/kakaoLoginAPI.ts
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoCallBack.tsx
  src/state/loginState.ts
  yarn.lock
Labels: function

#48 1차 검토를 위한 현재까지 진행상황 merge
  package-lock.json
  package.json
  src/api/shareRoomAPI.ts
  src/assets/leftArrow.svg
  src/assets/rightArrow.svg
  src/auth/auth.ts
  src/components/common/footer/Footer.tsx
  src/components/common/header/HeaderContainer.tsx
  src/components/main/Problem.tsx
  src/components/main/Resolve.tsx
  src/components/main/Start.tsx
  src/components/main/Step.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareEntrance/createShareRoomModal/Close.tsx
  src/components/planShareEntrance/createShareRoomModal/PlanDate.tsx
  src/components/planShareEntrance/createShareRoomModal/Title.tsx
  src/components/planShareEntrance/planList/PlanList.tsx
  src/components/planShareEntrance/planList/planContent/ExistsPlan.tsx
  src/components/planShareEntrance/planList/planContent/NotExistsPlan.tsx
  src/components/planShareEntrance/planList/planContent/PlanListContent.tsx
  src/components/planShareEntrance/planList/planContent/SearchResult.tsx
  src/components/planShareEntrance/planList/planHeader/PlanListHeader.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/sideBar/SideBar.tsx
  src/components/planShareRoom/sideBar/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/sideBar/placeSearchArea/placeSearchAreaContent/PlaceSearchLists.tsx
  src/components/planShareRoom/sideBar/placeSearchArea/placeSearchAreaHeader/PlaceSearchAreaHeader.tsx
  src/components/planShareRoom/sideBar/placeSearchArea/placeSearchAreaHeader/PlaceSearchBar.tsx
  src/components/planShareRoom/sideBar/placeSearchArea/placeSearchAreaHeader/PlaceSearchCategory.tsx
  src/components/planShareRoom/sideBar/scheduleArea/DaySelect.tsx
  src/components/planShareRoom/sideBar/scheduleArea/PlaceLists.tsx
  src/components/planShareRoom/sideBar/scheduleArea/ScheduleArea.tsx
  src/components/planShareRoom/sideBar/scheduleArea/SideBarHeader.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/components/profileEdit/Tab.tsx
  src/components/profileEdit/edit/ProfileEditForm.tsx
  src/components/profileEdit/passwordEdit/PasswordEdit.tsx
  src/components/profileEdit/secession/Secession.tsx
  src/data/area.ts
  src/state/loginState.ts
  src/state/selectedArea.ts
  src/state/sidebarState.ts
  src/store/kakaoMap.ts
  src/store/placeSearchResult.ts
  src/store/searchShareRoom.ts
  src/store/shareRoomInfo.ts
  src/type/shareRoom.ts
  src/type/sideBarOpenState.ts
  tailwind.config.js
  yarn.lock
Labels: function, UI(Component)

#49 로그인 기능 추가 구현
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/headerRight/RightContainer.tsx
  src/components/common/header/headerRight/SignInAndUp.tsx
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoCallBack.tsx
  src/hooks/useLastLocation.ts
  src/hooks/useLoginState.ts
  src/state/lastLocationState.ts
  src/state/loginState.ts
Labels: function

#56 일정공유방 수정 기능 추가, CSS 수정
  index.html
  src/api/shareRoomAPI.ts
  src/assets/address.svg
  src/components/common/calendar/Calendar.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareEntrance/createShareRoomModal/CreateShareRoomModal.tsx
  src/components/planShareEntrance/createShareRoomModal/PlanDate.tsx
  src/components/planShareEntrance/createShareRoomModal/Title.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaHeader.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ScheduleArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/usePlanDate.ts
  src/hooks/useTitle.ts
  src/input.css
  src/store/shareRoomForm.ts
  src/utils/formValidationCheck.ts
  tailwind.config.js
Labels: function, UI(Component)

#58 í² Design: 일정공유방 css 수정
  src/components/common/calendar/Calendar.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaHeader.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchCategory.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchTitle.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/usePlanDate.ts
  tailwind.config.js
Labels: UI(Component)

#57 토큰 재발급 로직 생성
  src/api/shareRoomAPI.ts
  src/components/common/header/headerRight/SignInAndUp.tsx
  src/components/login/EmailLoginForm.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareEntrance/planList/PlanListContent.tsx
  src/components/planShareEntrance/planList/PlanListHeader.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
  src/hooks/useLoginState.ts
  src/utils/cookie.ts
Labels: bug, function

#59 Feature/new post
  src/api/newPostAPI.ts
  src/type/newPost.ts
Labels: function

#62 사이드바 일정영역 css 수정
  src/assets/menu.svg
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/SideBarToggle.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/state/sidebarState.ts
  src/type/sideBarOpenState.ts
Labels: UI(Component)

#63 Feature/community
  package-lock.json
  package.json
  src/App.tsx
  src/api/communityAPI.ts
  src/api/memberAPI.ts
  src/api/newPostAPI.ts
  src/api/postAPI.ts
  src/components/community/Category.tsx
  src/components/community/Lists.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/newPost/EditorArea.tsx
  src/hooks/useEditor.ts
  src/hooks/useMyShareRoom.ts
  src/pages/NewPost.tsx
  src/pages/Post.tsx
  src/type/communityPage.ts
  src/type/newPost.ts
  yarn.lock
Labels: function

#64 카카오맵 관련 코드 구조 변경
  index.html
  package-lock.json
  package.json
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/hooks/useShareRoomForm.ts
  src/type/kakaoMap.ts
  src/type/kakaoPlaceSearchResult.ts
  src/type/shareRoom.ts
  tsconfig.json
  yarn.lock
Labels: function

#65 Feature/profile
  src/api/profileAPI.ts
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/hooks/useMyShareRoom.ts
  src/type/profile.ts
Labels: function

#66 Feature/community
  package-lock.json
  package.json
  src/api/communityAPI.ts
  src/api/postAPI.ts
  src/assets/heartFill.svg
  src/assets/heartNoFill.svg
  src/components/community/Lists.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/Like.tsx
  src/components/newPost/EditorArea.tsx
  src/pages/Post.tsx
  src/type/communityPage.ts
  tailwind.config.js
  yarn.lock
Labels: function

#67 Feature/login
  src/auth/auth.ts
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/headerRight/RightContainer.tsx
  src/components/main/Start.tsx
  src/components/newPost/EditorArea.tsx
  src/components/planShareEntrance/planList/PlanListContent.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  src/hooks/useLoginState.ts
  src/hooks/useMyShareRoom.ts
  src/hooks/useRequireAuth.ts
  src/state/loginState.ts
  yarn.lock
Labels: function

#68 Feature/login
  src/api/kakaoLoginAPI.ts
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoCallBack.tsx
  src/components/login/KakaoLoginButton.tsx
  src/hooks/useLoginState.ts
  src/utils/cookie.ts
Labels: function

#69 일정 공유방 일차별 일정 조회 및 장소 추가 기능 추가
  src/api/destinationAPI.ts
  src/api/scheduleAPI.ts
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/NotExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/useManageSchdule.ts
  src/store/placeSearchResult.ts
  src/store/schedule.ts
  src/store/selectedDay.ts
  src/type/kakaoMap.ts
  src/type/shareRoom.ts
  src/utils/calculateDays.ts
Labels: function, UI(Component)

#70 Feature/community
  src/App.tsx
  src/api/newPostAPI.ts
  src/api/postAPI.ts
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/EditPost.tsx
  src/components/community/postPage/Post.tsx
  src/components/community/postPage/PostEditDelete.tsx
  src/hooks/usePost.ts
  src/pages/Post.tsx
  src/pages/PostPage.tsx
  src/type/communityPage.ts
Labels: function

#72 ✨ Feature: 일정공유방 생성 후에 로직 추가
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
Labels: function

#73 🐛 Fix: 일정 장소 컴포넌트 출력 조건 수정
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
Labels: bug

#74 날짜 계산 로직 수정하여 오류 해결
  src/components/common/calendar/Calendar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/constants/initial.ts
  src/hooks/usePlanDate.ts
  src/type/shareRoomForm.ts
  src/utils/calculateDays.ts
Labels: bug

#75 Fix: 쿠키에 중복된 key로 cookie 생성되는 오류 해결
  src/api/destinationAPI.ts
  src/api/scheduleAPI.ts
  src/api/shareRoomAPI.ts
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/participatingPlan/ParticipatingPlan.tsx
  src/components/profileEdit/Tab.tsx
  src/utils/cookie.ts
Labels: bug

#76 일정공유방 Map 및 페이지네이션 기능 추가
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchCategory.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/type/shareRoom.ts
Labels: bug, function

#77 커스텀 오버레이 장소추가 기능, 일정완료 기능 추가
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/NotExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/usePlanDate.ts
  src/state/travelDate.ts
  src/type/shareRoom.ts
Labels: function, UI(Component)

#78 일차별 추천경로로 일정 수정 기능 추가
  src/api/destinationAPI.ts
  src/api/recommendAPI.ts
  src/assets/arrowDirection.svg
  src/assets/flag.svg
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/hooks/useManageSchdule.ts
  src/state/selectStartPoint.ts
  src/store/schedule.ts
  src/type/startPoint.ts
Labels: function, UI(Component)

#79 Feature/community
  src/api/newPostAPI.ts
  src/components/community/Lists.tsx
  src/components/community/Pagination.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/Like.tsx
  src/components/community/postPage/PostEditDelete.tsx
  src/components/newPost/EditorArea.tsx
  src/hooks/useEditor.ts
  src/pages/CommunityPage.tsx
  src/type/communityPage.ts
  src/type/newPost.ts
Labels: function

#80 채팅 컴포넌트 및 stomp.js, socket.io 설치
  package-lock.json
  package.json
  src/assets/chatEmotion.svg
  src/components/planShareRoom/Chat.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  yarn.lock
Labels: function, UI(Component)

#81 일정공유방 로직 변경
  src/api/destinationAPI.ts
  src/api/recommendAPI.ts
  src/api/scheduleAPI.ts
  src/api/shareRoomAPI.ts
  src/components/common/calendar/Calendar.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/NotExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleArea.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/constants/marker.ts
  src/hooks/useManageSchdule.ts
  src/hooks/usePlanDate.ts
  src/hooks/useShareRoomForm.ts
  src/state/componentOpenState.ts
  src/store/schedule.ts
  src/utils/calculateDays.ts
Labels: bug, function, UI(Component)

#83 Feature/community
  src/api/memberAPI.ts
  src/api/newPostAPI.ts
  src/components/community/Lists.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/Post.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/type/communityPage.ts
  vite.config.ts
Labels: function

#84 Feature/chat
  src/api/chatAPI.ts
  src/components/community/postPage/CreateComment.tsx
  src/components/planShareEntrance/createShareRoomModal/Button.tsx
  src/components/planShareRoom/Chat.tsx
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
Labels: function

#85 일정완료 기능, 완료 시 카카오톡 전송 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/kakaoLoginAPI.ts
  src/api/scheduleAPI.ts
  src/api/shareRoomAPI.ts
  src/components/common/spinner/Spinner.tsx
  src/components/planShareEntrance/planList/PlanListContent.tsx
  src/components/planShareRoom/KaKaoSendImage.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/utils/calculateDays.ts
  src/utils/cookie.ts
  yarn.lock
Labels: function

#86 장소추천 기능 추가
  src/api/recommendAPI.ts
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/placeSearchArea/PlaceRecommendList.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchArea.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchAreaContent.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchCategory.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/hooks/useManageSchdule.ts
  src/state/recommendState.ts
  src/store/recommendPlaceList.ts
  src/type/kakaoMap.ts
  src/type/shareRoom.ts
Labels: function

#88 일차 선택 시 출력되는 날짜 계속 오류 수정
  src/utils/calculateDays.ts
Labels: bug

#91 Feature/style
  Test.lcok
  src/api/userSignUp.ts
  src/assets/arrow-left-circle.svg
  src/assets/arrow-right-circle.svg
  src/components/common/header/HeaderContainer.tsx
  src/components/community/Lists.tsx
  src/components/community/Pagination.tsx
  src/components/community/SearchBar.tsx
  src/components/community/SortButtons.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/EditPost.tsx
  src/components/community/postPage/Like.tsx
  src/components/community/postPage/Post.tsx
  src/components/community/postPage/PostEditDelete.tsx
  src/components/login/EmailLoginForm.tsx
  src/components/login/KakaoLoginButton.tsx
  src/components/login/LoginHeader.tsx
  src/components/login/SignUpLink.tsx
  src/components/main/Start.tsx
  src/components/newPost/EditorArea.tsx
  src/components/signUp/signUpForm.tsx
  src/pages/CommunityPage.tsx
  src/pages/PostPage.tsx
  tailwind.config.js
Labels: UI

#92 Feature/profile edit
  src/api/memberAPI.ts
  src/api/profileAPI.ts
  src/components/profileEdit/edit/ProfileEditForm.tsx
Labels: function

#93 🐛 Fix: 날짜 선택 후 다시 선택 시 선택 안할경우에도 저장되는 오류 수정
  src/components/common/calendar/Calendar.tsx
  src/hooks/usePlanDate.ts
Labels: bug

#94 Feature/style
  src/components/common/header/HeaderContainer.tsx
  src/components/common/header/headerLeft/LeftContainer.tsx
  src/components/common/header/headerLeft/Logo.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/headerRight/SignInAndUp.tsx
  src/components/community/Lists.tsx
  src/components/community/Pagination.tsx
  src/components/community/postPage/Comment.tsx
  src/components/community/postPage/CreateComment.tsx
  src/components/community/postPage/Post.tsx
  src/components/login/LoginHeader.tsx
  src/components/planShareEntrance/planList/ExistsPlan.tsx
  src/components/planShareEntrance/searchCodeBar/SearchCodeBar.tsx
  src/components/profile/Profile.tsx
  src/components/profile/participatingPlan/ExistsParticipatingPlan.tsx
  src/components/profile/profileUserInfo/ProfileUserInfo.tsx
  tailwind.config.js
Labels: UI(Component)

#95 Feature/chat
  index.html
  src/components/planShareRoom/Chat.tsx
Labels: function

#96 일차별 일정 메모 기능 추가
  src/api/scheduleAPI.ts
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/components/planShareRoom/scheduleArea/ScheduleAreaHeader.tsx
  src/components/planShareRoom/scheduleArea/ScheduleDaySelect.tsx
  src/components/planShareRoom/scheduleArea/ScheduleLists.tsx
  src/components/planShareRoom/scheduleArea/ScheduleMemo.tsx
  src/state/componentOpenState.ts
  src/state/memberInfo.ts
Labels: function, UI(Component)

#97 일차별 일정 목적지 마커 출력 및 목적지와 목적지 사이 선 출력되게 수정
  src/components/planShareRoom/PlanShareRoom.tsx
  src/components/planShareRoom/SideBar.tsx
  src/components/planShareRoom/placeSearchArea/PlaceRecommendList.tsx
  src/components/planShareRoom/placeSearchArea/PlaceSearchLists.tsx
  src/components/planShareRoom/scheduleArea/ExistsSchedule.tsx
  src/hooks/useManageSchdule.ts
  src/state/scheduleMarkerState.ts
Labels: function, UI(Component)
